# Generated by Django 5.1.5 on 2025-01-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user",
        ),
    ]
