# Generated by Django 5.1.5 on 2025-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("FACTORY", "Factory"),
                    ("RETAIL", "Retail"),
                    ("INDIVIDUAL", "Individual entrepreneur"),
                ],
                help_text="Укажите тип клиента",
                max_length=100,
                verbose_name="Тип клиента",
            ),
        ),
    ]
