# Generated by Django 5.1.5 on 2025-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_client_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("FACTORY", "Завод"),
                    ("RETAIL", "Розничная сеть"),
                    ("INDIVIDUAL", "Индивидуальный предприниматель"),
                ],
                help_text="Укажите тип клиента",
                max_length=100,
                verbose_name="Тип клиента",
            ),
        ),
    ]
