# Generated by Django 5.1.5 on 2025-01-23 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_client_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("FACTORY", "Завод"),
                    ("RETAIL", "Розничная сеть"),
                    ("INDIVIDUAL", "Индивидуальный предприниматель"),
                ],
                max_length=100,
                verbose_name="Тип клиента",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=30, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Наименование организации"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_supplier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Поставщик",
            ),
        ),
    ]
