# Generated by Django 5.1.5 on 2025-01-19 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название продукта",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model_product",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель продукта",
                        max_length=255,
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте описание продукта",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото",
                        null=True,
                        upload_to="products/photo/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте если в продаже",
                        verbose_name="В продаже",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату выхода на рынок",
                        null=True,
                        verbose_name="Дата выхода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите доступное количество",
                        verbose_name="Количество",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        default=0, help_text="Укажите стоимость", verbose_name="Цена"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_warehouse",
                        to="products.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_warehouse",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт на склад",
                "verbose_name_plural": "Продукты на Складе",
            },
        ),
    ]
