# Generated by Django 5.1.5 on 2025-01-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_warehouse_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "verbose_name": "Продукт на склад",
                "verbose_name_plural": "Продукты на Складах",
            },
        ),
    ]
